name: Build P4Php for Windows

env:
  codeline:       "r20.1"
  docker:         "ghcr.io/ppiorunski/server2019-vs2017-p4php"
  phpMount:       "${{ github.workspace }}\\..\\php-src:c:\\dependencies\\php"
  p4apiMount:     "${{ github.workspace }}\\..\\p4api:c:\\dependencies\\p4api"
  p4phpBinMount:  "${{ github.workspace }}\\..\\p4-bin:c:\\p4php-bin"
  phpSdkMount:    "${{ github.workspace }}\\..\\php-sdk-binary-tools:c:\\dependencies\\php-sdk-binary-tools"
  p4phpMount:     "${{ github.workspace }}:c:\\dependencies\\p4php-source"
  #phpMinor: "2"
  # phpMajor: "7" unused
  libname: "p4-bin\\%bin%\\perforce_php7%PHP_MINOR_VER%"
  username: ${{ secrets.DOCKERHUB_USERNAME }}
  password: ${{ secrets.GITHUBREGISTRY_TOKEN }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        TS: [TS, NTS]
        phpMinor: [2, 3, 4]
        arch: [x86, x64]
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      with:
        path: p4php/

    - name: Login to docker hub
      run: |
        echo $env:password| docker login ghcr.io --username $env:username --password-stdin
    - name: Get p4api and p4 binary
      run: |
        cd ..\
        $WebClient = New-Object System.Net.WebClient ; $WebClient.DownloadFile("ftp://ftp.perforce.com/perforce/$env:codeline/bin.nt${{ matrix.arch }}/p4api_vs2017_dyn_openssl1.1.1.zip","${{ github.workspace }}\..\p4api.zip")
        Expand-Archive -Path ${{ github.workspace }}\..\p4api.zip ;  Move-Item -path ${{ github.workspace }}\..\p4api\*\* ${{ github.workspace }}\..\p4api\

        # 2 ways to get the php src - git clone and sync @tag, or download from website.
        #$WebClient = New-Object System.Net.WebClient ; $WebClient.DownloadFile("https://codeload.github.com/php/php-src/zip/php-7.4.10","${{ github.workspace }}\..\php-src.zip")
        #Expand-Archive -Path ${{ github.workspace }}\..\php-src.zip ;  Move-Item -path ${{ github.workspace }}\..\php-src\*\* ${{ github.workspace }}\..\php-src\

        cd ${{ github.workspace }}\.. ; git clone https://github.com/php/php-src.git ; cd php-src ; git checkout tags/php-7.${{ matrix.phpMinor }}.10
        $WebClient = New-Object System.Net.WebClient ; $WebClient.DownloadFile("ftp://ftp.perforce.com/perforce/$env:codeline/bin.nt${{ matrix.arch }}/p4.exe","${{ github.workspace }}\..\php-src\p4.exe")
        $WebClient = New-Object System.Net.WebClient ; $WebClient.DownloadFile("ftp://ftp.perforce.com/perforce/$env:codeline/bin.nt${{ matrix.arch }}/p4d.exe","${{ github.workspace }}\..\php-src\p4d.exe")

        cd ${{ github.workspace }}\.. ; git clone  https://github.com/microsoft/php-sdk-binary-tools.git ; cd php-sdk-binary-tools ;git checkout tags/php-sdk-2.2.0
        cd ${{ github.workspace }}\..

        mkdir ${{ github.workspace }}\..\p4-bin
        dir  ${{ github.workspace }}\..
        dir  ${{ github.workspace }}\..\..
        # note to self when dir is changed it stays that way between commands
        dir
        dir p4-bin
        dir p4api
        dir p4-bin
        dir p4php7
        dir p4php7/p4php
        dir  php-sdk-binary-tools
        dir php-src


    - name: Get docker image
      run: docker pull $Env:docker
    - name: Build P4Php 7.2 Openssl 1.1.1
      run: |
        docker run `
        -v $Env:phpMount `
        -v $Env:p4phpMount `
        -v $Env:p4apiMount `
        -v $Env:p4phpBinMount `
        -v $Env:phpSdkMount `
        --env PHP_MINOR_VER=${{ matrix.phpMinor }} --env arch=${{ matrix.arch }} --env TS=${{ matrix.TS }} `
        $Env:docker
        dir ${{ github.workspace }}\..\p4-bin
        move ${{ github.workspace }}\..\p4-bin\perforce_php7${{ matrix.phpMinor }}${{ matrix.TS }}.dll ${{ github.workspace }}\perforce_php7${{ matrix.phpMinor }}_${{ matrix.arch }}_${{ matrix.TS }}.dll


    - uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}\perforce_php7${{ matrix.phpMinor }}_${{ matrix.arch }}_${{ matrix.TS }}
