name: Build P4Php for php 7.2 linux OpenSSL 1.1.1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set-up-vm
      run: |
        sudo apt-get update
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get install -qq  php7.2-dev make build-essential dialog apt-utils re2c wget
        pwd
        ls
        cd .. && wget ftp://ftp.perforce.com/perforce/r20.1/bin.linux26x86_64/p4api-glibc2.3-openssl1.1.1.tgz
        tar -xvf p4api-glibc2.3-openssl1.1.1.tgz && mv p4api* pkapi && ls -la && cd p4php7 && pwd
        make clean
        phpize
        ./configure --with-perforce=../p4api
        make
        make test
        
        
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
