name: Build P4Php for php 7.2 linux OpenSSL 1.1.1

env:
  codeline: "r20.1"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build P4Php 7.2 Openssl 1.1.1

      run: |
        sudo apt-get update
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get install -qq  php7.2-dev make build-essential dialog apt-utils re2c wget
        pwd
        ls
        docker images
        cat /etc/group
        cd .. && wget ftp://ftp.perforce.com/perforce/$codeline/bin.linux26x86_64/p4api-glibc2.3-openssl1.1.1.tgz
        tar -xvf p4api-glibc2.3-openssl1.1.1.tgz && rm p4api-glibc2.3-openssl1.1.1.tgz && mv p4api* p4api && ls -la && cd p4php7 && pwd
        wget ftp://ftp.perforce.com/perforce/$codeline/bin.linux26x86_64/p4 && chmod 775 p4
        wget ftp://ftp.perforce.com/perforce/$codeline/bin.linux26x86_64/p4d && chmod 775 p4d
        phpize
        ./configure --with-perforce=../p4api
        make
        make test
    - uses: actions/upload-artifact@v2
      with:
        path: modules/perforce.so


#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
